[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"
  environment = { REACT_APP_API_URL = "http://localhost:8000/api" }

[context.production]
  environment = { REACT_APP_API_URL = "https://taskmanager-production-617c.up.railway.app/api" }
